//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;

    public partial class Bills
    {
        public int BillId { get; set; }
        public int ReservationID { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal Amount { get; set; }
        public string Discription { get; set; }
        public int BillType { get; set; }
    
        public virtual BillsTypes BillsTypes { get; set; }
        public virtual Reservations Reservations { get; set; }
    }
}
