//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drugs()
        {
            this.BuyingInvoiceDetail = new HashSet<BuyingInvoiceDetail>();
            this.PrescriptionDetail = new HashSet<PrescriptionDetail>();
        }
    
        public int DrugId { get; set; }
        public string DrugName { get; set; }
        public int DrugUnit { get; set; }
        public decimal PricePerUnit { get; set; }
        public int Balance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyingInvoiceDetail> BuyingInvoiceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionDetail> PrescriptionDetail { get; set; }
        public virtual DrugUnits DrugUnits { get; set; }
    }
}
