//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class hospitalEntities : DbContext
    {
        public hospitalEntities()
            : base("name=hospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<BillsTypes> BillsTypes { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<BuyingInvoice> BuyingInvoice { get; set; }
        public virtual DbSet<BuyingInvoiceDetail> BuyingInvoiceDetail { get; set; }
        public virtual DbSet<SupplierAddress> SupplierAddress { get; set; }
        public virtual DbSet<SupplierContact> SupplierContact { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<RoomsDegree> RoomsDegree { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<ScientificDegree> ScientificDegree { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<bloodGroups> bloodGroups { get; set; }
        public virtual DbSet<Diseases> Diseases { get; set; }
        public virtual DbSet<DocfollowUp> DocfollowUp { get; set; }
        public virtual DbSet<Fellow> Fellow { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientMeasures> PatientMeasures { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<DrugUnits> DrugUnits { get; set; }
        public virtual DbSet<Prescription> Prescription { get; set; }
        public virtual DbSet<PrescriptionDetail> PrescriptionDetail { get; set; }
    }
}
