//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hospitalEntities : DbContext
    {
        public hospitalEntities()
            : base("name=hospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<BillsTypes> BillsTypes { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<BuyingInvoice> BuyingInvoice { get; set; }
        public virtual DbSet<BuyingInvoiceDetail> BuyingInvoiceDetail { get; set; }
        public virtual DbSet<SupplierAddress> SupplierAddress { get; set; }
        public virtual DbSet<SupplierContact> SupplierContact { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<RoomsDegree> RoomsDegree { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<ScientificDegree> ScientificDegree { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<bloodGroups> bloodGroups { get; set; }
        public virtual DbSet<Diseases> Diseases { get; set; }
        public virtual DbSet<DocfollowUp> DocfollowUp { get; set; }
        public virtual DbSet<Fellow> Fellow { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientMeasures> PatientMeasures { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<DrugUnits> DrugUnits { get; set; }
        public virtual DbSet<Prescription> Prescription { get; set; }
        public virtual DbSet<PrescriptionDetail> PrescriptionDetail { get; set; }
    
        public virtual int Cproc_AddBillsType(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddBillsType", nameParameter);
        }
    
        public virtual int Cproc_AddBloodGroup(string bloodGroupName)
        {
            var bloodGroupNameParameter = bloodGroupName != null ?
                new ObjectParameter("BloodGroupName", bloodGroupName) :
                new ObjectParameter("BloodGroupName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddBloodGroup", bloodGroupNameParameter);
        }
    
        public virtual int Cproc_AddDiseases(string diseaseName)
        {
            var diseaseNameParameter = diseaseName != null ?
                new ObjectParameter("DiseaseName", diseaseName) :
                new ObjectParameter("DiseaseName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddDiseases", diseaseNameParameter);
        }
    
        public virtual int Cproc_AddDrug(string drugName, Nullable<int> drugUnit, Nullable<decimal> pricePerUnit, Nullable<int> balance)
        {
            var drugNameParameter = drugName != null ?
                new ObjectParameter("DrugName", drugName) :
                new ObjectParameter("DrugName", typeof(string));
    
            var drugUnitParameter = drugUnit.HasValue ?
                new ObjectParameter("DrugUnit", drugUnit) :
                new ObjectParameter("DrugUnit", typeof(int));
    
            var pricePerUnitParameter = pricePerUnit.HasValue ?
                new ObjectParameter("PricePerUnit", pricePerUnit) :
                new ObjectParameter("PricePerUnit", typeof(decimal));
    
            var balanceParameter = balance.HasValue ?
                new ObjectParameter("balance", balance) :
                new ObjectParameter("balance", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddDrug", drugNameParameter, drugUnitParameter, pricePerUnitParameter, balanceParameter);
        }
    
        public virtual int Cproc_AddDrugUnits(string dtugUnitName)
        {
            var dtugUnitNameParameter = dtugUnitName != null ?
                new ObjectParameter("DtugUnitName", dtugUnitName) :
                new ObjectParameter("DtugUnitName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddDrugUnits", dtugUnitNameParameter);
        }
    
        public virtual int Cproc_AddFellow(string fellowname, string soSeNo, string phoneNumber, Nullable<int> patientId)
        {
            var fellownameParameter = fellowname != null ?
                new ObjectParameter("Fellowname", fellowname) :
                new ObjectParameter("Fellowname", typeof(string));
    
            var soSeNoParameter = soSeNo != null ?
                new ObjectParameter("SoSeNo", soSeNo) :
                new ObjectParameter("SoSeNo", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            var patientIdParameter = patientId.HasValue ?
                new ObjectParameter("patientId", patientId) :
                new ObjectParameter("patientId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddFellow", fellownameParameter, soSeNoParameter, phoneNumberParameter, patientIdParameter);
        }
    
        public virtual int Cproc_AddNewDoc(string docName, string docAddress, string docphone, Nullable<int> docDegree, Nullable<int> docSpecification, Nullable<bool> gender)
        {
            var docNameParameter = docName != null ?
                new ObjectParameter("DocName", docName) :
                new ObjectParameter("DocName", typeof(string));
    
            var docAddressParameter = docAddress != null ?
                new ObjectParameter("DocAddress", docAddress) :
                new ObjectParameter("DocAddress", typeof(string));
    
            var docphoneParameter = docphone != null ?
                new ObjectParameter("Docphone", docphone) :
                new ObjectParameter("Docphone", typeof(string));
    
            var docDegreeParameter = docDegree.HasValue ?
                new ObjectParameter("DocDegree", docDegree) :
                new ObjectParameter("DocDegree", typeof(int));
    
            var docSpecificationParameter = docSpecification.HasValue ?
                new ObjectParameter("DocSpecification", docSpecification) :
                new ObjectParameter("DocSpecification", typeof(int));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddNewDoc", docNameParameter, docAddressParameter, docphoneParameter, docDegreeParameter, docSpecificationParameter, genderParameter);
        }
    
        public virtual int Cproc_AddPatientMeasure(Nullable<int> patientId, Nullable<int> diseaseId, string measureResult, Nullable<System.DateTime> timeOfMeasure, string remarks, Nullable<int> doctorId)
        {
            var patientIdParameter = patientId.HasValue ?
                new ObjectParameter("patientId", patientId) :
                new ObjectParameter("patientId", typeof(int));
    
            var diseaseIdParameter = diseaseId.HasValue ?
                new ObjectParameter("DiseaseId", diseaseId) :
                new ObjectParameter("DiseaseId", typeof(int));
    
            var measureResultParameter = measureResult != null ?
                new ObjectParameter("MeasureResult", measureResult) :
                new ObjectParameter("MeasureResult", typeof(string));
    
            var timeOfMeasureParameter = timeOfMeasure.HasValue ?
                new ObjectParameter("TimeOfMeasure", timeOfMeasure) :
                new ObjectParameter("TimeOfMeasure", typeof(System.DateTime));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            var doctorIdParameter = doctorId.HasValue ?
                new ObjectParameter("DoctorId", doctorId) :
                new ObjectParameter("DoctorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddPatientMeasure", patientIdParameter, diseaseIdParameter, measureResultParameter, timeOfMeasureParameter, remarksParameter, doctorIdParameter);
        }
    
        public virtual int cproc_AddRooms(Nullable<int> roomDegree, string roomfloor, string roomNo)
        {
            var roomDegreeParameter = roomDegree.HasValue ?
                new ObjectParameter("RoomDegree", roomDegree) :
                new ObjectParameter("RoomDegree", typeof(int));
    
            var roomfloorParameter = roomfloor != null ?
                new ObjectParameter("Roomfloor", roomfloor) :
                new ObjectParameter("Roomfloor", typeof(string));
    
            var roomNoParameter = roomNo != null ?
                new ObjectParameter("RoomNo", roomNo) :
                new ObjectParameter("RoomNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cproc_AddRooms", roomDegreeParameter, roomfloorParameter, roomNoParameter);
        }
    
        public virtual int Cproc_AddRoomsDegree(string name, Nullable<decimal> feesDay, string discription)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var feesDayParameter = feesDay.HasValue ?
                new ObjectParameter("FeesDay", feesDay) :
                new ObjectParameter("FeesDay", typeof(decimal));
    
            var discriptionParameter = discription != null ?
                new ObjectParameter("Discription", discription) :
                new ObjectParameter("Discription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddRoomsDegree", nameParameter, feesDayParameter, discriptionParameter);
        }
    
        public virtual int Cproc_AddSpecialization(string specificationName)
        {
            var specificationNameParameter = specificationName != null ?
                new ObjectParameter("SpecificationName", specificationName) :
                new ObjectParameter("SpecificationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddSpecialization", specificationNameParameter);
        }
    
        public virtual int Cproc_AddSupplierAddress(Nullable<int> supplierID, string supplierAddress)
        {
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("supplierID", supplierID) :
                new ObjectParameter("supplierID", typeof(int));
    
            var supplierAddressParameter = supplierAddress != null ?
                new ObjectParameter("supplierAddress", supplierAddress) :
                new ObjectParameter("supplierAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddSupplierAddress", supplierIDParameter, supplierAddressParameter);
        }
    
        public virtual int Cproc_AddSupplierContact(string contactName, string jobtitle, string telephone, Nullable<int> addressId)
        {
            var contactNameParameter = contactName != null ?
                new ObjectParameter("contactName", contactName) :
                new ObjectParameter("contactName", typeof(string));
    
            var jobtitleParameter = jobtitle != null ?
                new ObjectParameter("jobtitle", jobtitle) :
                new ObjectParameter("jobtitle", typeof(string));
    
            var telephoneParameter = telephone != null ?
                new ObjectParameter("telephone", telephone) :
                new ObjectParameter("telephone", typeof(string));
    
            var addressIdParameter = addressId.HasValue ?
                new ObjectParameter("addressId", addressId) :
                new ObjectParameter("addressId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddSupplierContact", contactNameParameter, jobtitleParameter, telephoneParameter, addressIdParameter);
        }
    
        public virtual int Cproc_AddSuppliers(string supplierName)
        {
            var supplierNameParameter = supplierName != null ?
                new ObjectParameter("SupplierName", supplierName) :
                new ObjectParameter("SupplierName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_AddSuppliers", supplierNameParameter);
        }
    
        public virtual int Cproc_DocDegrees(string scientificDegreeName)
        {
            var scientificDegreeNameParameter = scientificDegreeName != null ?
                new ObjectParameter("ScientificDegreeName", scientificDegreeName) :
                new ObjectParameter("ScientificDegreeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cproc_DocDegrees", scientificDegreeNameParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
