//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMeasure
    {
        public int PatientID { get; set; }
        public int DiseaseID { get; set; }
        public string MeasureResult { get; set; }
        public System.DateTime TimeOfMeasure { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Disease Disease { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
