//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierContact
    {
        public string ContactName { get; set; }
        public string JobTitle { get; set; }
        public string ContactPhone { get; set; }
        public int AddressId { get; set; }
    
        public virtual SupplierAddress SupplierAddress { get; set; }
    }
}
