//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Prescription
    {
        public int ReservationID { get; set; }
        public int Qnty { get; set; }
        public decimal PricePerUnit { get; set; }
        public bool IsReceived { get; set; }
    }
}
